package org.mifosplatform.billing.selfcare.exception;

import org.mifosplatform.infrastructure.core.exception.AbstractPlatformDomainRuleException;

public class SelfCareTemporaryGeneratedKeyNotFoundException extends AbstractPlatformDomainRuleException{

	public SelfCareTemporaryGeneratedKeyNotFoundException(final String generatedKey){
		 super("error.msg.billing.generatedKey.not.found", "AutoGenerated Key not found with this " + generatedKey);
	}
}
